#284:Remove python2 from standard-EXASOL-7.1.0
exasol/script-languages-release pull request #285
Opened 2021-07-06 20:31 UTC by tomuben

2021-07-07 07:20 UTC, tkilias requested changes
Besides my code comments, you probably need also to cleanup the apt_packages for the flavor_base_deps build step

2021-07-07 07:20 UTC, tkilias commented on flavors/standard-EXASOL-7.1.0/flavor_base/build_run/Dockerfile
> +RUN cp -r -L bazel-bin/* /exaudf && rm -r /exaudf/external/bazel_tools/ && rm -r /exaudf/exaudfclient
Only, deleting /exaudf/exaudfclient is probably not enough, you also should exclude it from the build by changing `--config fast-binary-both` to  `--config fast-binary-py3`, similar for base_test_build_run/Dockerfile

2021-07-07 18:11 UTC, tomuben commented
In order to remove also ```libpython2.7```, we would have to remove ```python3-smbc```.
Dependency chain: python3-smbc => libsmbclient => samba-libs => libpython2.7.

2021-07-08 12:15 UTC, tkilias approved these changes

2021-07-09 17:32 UTC, tomuben commented
@tkilias , please check.
Latest changes:
1. Remove the python-smbc chec
2. Revert of using the EXASOL Websocket pinned version.

2021-07-12 10:36 UTC, merged