#595: Fixed content of contributing.md
exasol/script-languages-release pull request #598
Opened 2022-05-12 12:54 UTC by tomuben

We decided to keep the contributing.md as general as possible as we plan to split the script-languages repository during the next couple of months.

### All Submissions:

* [ ] Check if your pull request goes to the correct bash branch (develop or master)?
* [ ] Is the title of the Pull Request correct?
* [ ] Is the title of the corresponding issue correct?
* [ ] Have you updated the changelog?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../../pulls) for the same update/change?  
* [ ] Are you mentioning the issue which this PullRequest fixes ("Fixes...")

### When integrating to Develop branch:

1. [ ] Remember to merge with "Squash and Merge"

### When integrating to Main branch:

1. [ ] Remember to merge with "Merge"

2022-05-12 14:14 UTC, kaklakariada requested changes

2022-05-12 14:14 UTC, kaklakariada commented on contributing.md
> +- If, you are more experienced, we are happy about any pull request:
```suggestion
- If you are more experienced, we are happy about any pull request: 
```

2022-05-12 15:41 UTC, umitbuyuksahin approved these changes

2022-05-13 07:45 UTC, kaklakariada approved these changes

2022-05-13 09:29 UTC, merged