Feature/883 updated standard 8 slc
exasol/script-languages-release pull request #886
Opened 2024-05-06 17:38 UTC by tomuben

fixes #883 
### All Submissions:

* [ ] Check if your pull request goes to the correct bash branch (develop or master)?
* [ ] Is the title of the Pull Request correct?
* [ ] Is the title of the corresponding issue correct?
* [ ] Have you updated the changelog?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../../pulls) for the same update/change?  
* [ ] Are you mentioning the issue which this PullRequest fixes ("Fixes...")

### When integrating to Develop branch:

1. [ ] Remember to merge with "Squash and Merge"

### When integrating to Main branch:

1. [ ] Remember to merge with "Merge"

2024-05-10 04:46 UTC, kaklakariada requested changes

2024-05-10 04:46 UTC, kaklakariada commented on doc/changes/changes_8.0.0.md
> +Standard flavors (7.1 and 8.0) are simplified into a single flavor. The standard flavor now is based on Ubuntu 22.04 and support Python3.10 and R4.4.
```suggestion
Standard flavors (7.1 and 8.0) are simplified into a single flavor. The standard flavor now is based on Ubuntu 22.04 and supports Python3.10 and R4.4.
```

2024-05-10 12:54 UTC, tomuben commented on doc/changes/changes_8.0.0.md
> +Standard flavors (7.1 and 8.0) are simplified into a single flavor. The standard flavor now is based on Ubuntu 22.04 and support Python3.10 and R4.4.
Fixed

2024-05-10 12:55 UTC, tkilias submitted a review, later dismissed

2024-05-13 06:52 UTC, tkilias approved these changes

2024-05-13 09:41 UTC, kaklakariada approved these changes

2024-05-13 09:48 UTC, merged